# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedTradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('analyzed_trade_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtt.AnalyzedTradeInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.FloatField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_country', to='gtt.Country')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_partner', to='gtt.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=4)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_country', to='gtt.Country')),
                ('direction_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtt.DirectionType')),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_partner', to='gtt.Country')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtt.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtt.Template'),
        ),
        migrations.AddField(
            model_name='analyzedtradeinfo',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_trade_country', to='gtt.Country'),
        ),
        migrations.AddField(
            model_name='analyzedtradeinfo',
            name='direction_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtt.DirectionType'),
        ),
        migrations.AddField(
            model_name='analyzedtradeinfo',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_trade_partner', to='gtt.Country'),
        ),
    ]
