# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtt', '0003_auto_20170520_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedtradeinfo',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='used',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='tradeinfo',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
